DROP TABLE IF EXISTS contact CASCADE;
CREATE TABLE contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

INSERT INTO contact (id, first_name, last_name, email, phone) VALUES (1000, 'Ivan', 'Ivanov', 'iivanov@gmail.com', '1234567');
INSERT INTO contact (id, first_name, last_name, email, phone) VALUES (2000, 'Maria', 'Ivanova', 'mivanova@gmail.com', '7654321');
